Repository scoala-online/main, pull requests merged in 2021-09, with the labels that each got.

#11 docs: ✏️ add pull request template
  .github/pull_request_template.md
  README.md
  decorate-angular-cli.js
Labels: docs ✏️

#37 Feat/#35 implement service layer interface
  apps/java-api/src/main/java/org/scoalaonline/api/service/ServiceInterface.java
Labels: docs ✏️, feat 🎸, wiki 🌎, rest-api 🛰

#39 fix: 🐛 Change findOneById method to return Optional<T> object
  apps/java-api/src/main/java/org/scoalaonline/api/service/ServiceInterface.java
Labels: fix 🐛

#34 Docs/#14 create a readme file
  README.md
  package-lock.json
Labels: docs ✏️, wiki 🌎

#40 Feat/#22 implement lecture material endpoint
  apps/java-api/pom.xml
  apps/java-api/src/main/java/org/scoalaonline/api/controller/LectureMaterialController.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/LectureMaterialInvalidDocumentException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/LectureMaterialNotFoundException.java
  apps/java-api/src/main/java/org/scoalaonline/api/model/LectureMaterial.java
  apps/java-api/src/main/java/org/scoalaonline/api/repository/LectureMaterialRepository.java
  apps/java-api/src/main/java/org/scoalaonline/api/service/LectureMaterialService.java
  apps/java-api/src/main/java/org/scoalaonline/api/service/ServiceInterface.java
  apps/java-api/src/main/resources/.env-template
  apps/java-api/src/main/resources/application-dev.properties
Labels: docs ✏️, feat 🎸, wiki 🌎, rest-api 🛰

#43 Feat/#18 implement subject endpoint
  apps/java-api/pom.xml
  apps/java-api/src/main/java/org/scoalaonline/api/controller/SubjectController.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/SubjectInvalidValueException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/SubjectNotFoundException.java
  apps/java-api/src/main/java/org/scoalaonline/api/model/Subject.java
  apps/java-api/src/main/java/org/scoalaonline/api/repository/SubjectRepository.java
  apps/java-api/src/main/java/org/scoalaonline/api/service/SubjectService.java
Labels: feat 🎸

#50 update pull request template
  .github/pull_request_template.md
Labels: fix 🐛

#48 Feat/#15 user authentication
  apps/java-api/pom.xml
  apps/java-api/src/main/java/org/scoalaonline/api/DTO/RegisterForm.java
  apps/java-api/src/main/java/org/scoalaonline/api/JavaApiApplication.java
  apps/java-api/src/main/java/org/scoalaonline/api/controller/LectureMaterialController.java
  apps/java-api/src/main/java/org/scoalaonline/api/controller/RoleController.java
  apps/java-api/src/main/java/org/scoalaonline/api/controller/SubjectController.java
  apps/java-api/src/main/java/org/scoalaonline/api/controller/UserController.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/lectureMaterial/LectureMaterialInvalidDocumentException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/lectureMaterial/LectureMaterialNotFoundException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/role/RoleInvalidNameException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/role/RoleNotFoundException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/subject/SubjectInvalidValueException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/subject/SubjectNotFoundException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/user/UserInvalidNameException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/user/UserInvalidPasswordException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/user/UserInvalidRolesException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/user/UserInvalidUsernameException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/user/UserNotFoundException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/user/UserUsernameAlreadyUsedException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/user/UserUsernameNotAllowedException.java
  apps/java-api/src/main/java/org/scoalaonline/api/filter/CustomAuthenticationFilter.java
  apps/java-api/src/main/java/org/scoalaonline/api/filter/CustomAuthorizationFilter.java
  apps/java-api/src/main/java/org/scoalaonline/api/model/Role.java
  apps/java-api/src/main/java/org/scoalaonline/api/model/User.java
  apps/java-api/src/main/java/org/scoalaonline/api/repository/RoleRepository.java
  apps/java-api/src/main/java/org/scoalaonline/api/repository/UserRepository.java
  apps/java-api/src/main/java/org/scoalaonline/api/security/SecurityConfig.java
  apps/java-api/src/main/java/org/scoalaonline/api/security/UserSecurity.java
  apps/java-api/src/main/java/org/scoalaonline/api/service/JWTService.java
  apps/java-api/src/main/java/org/scoalaonline/api/service/LectureMaterialService.java
  apps/java-api/src/main/java/org/scoalaonline/api/service/RoleService.java
  apps/java-api/src/main/java/org/scoalaonline/api/service/SubjectService.java
  apps/java-api/src/main/java/org/scoalaonline/api/service/UserService.java
Labels: feat 🎸

#56 Docs/#54 update readme
  README.md
  package-lock.json
Labels: docs ✏️, wiki 🌎

#55 Feat/#19 implement grade endpoint
  apps/java-api/src/main/java/org/scoalaonline/api/controller/GradeController.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/grade/GradeInvalidValueException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/grade/GradeNotFoundException.java
  apps/java-api/src/main/java/org/scoalaonline/api/model/Grade.java
  apps/java-api/src/main/java/org/scoalaonline/api/repository/GradeRepository.java
  apps/java-api/src/main/java/org/scoalaonline/api/security/SecurityConfig.java
  apps/java-api/src/main/java/org/scoalaonline/api/service/GradeService.java
Labels: docs ✏️, feat 🎸, wiki 🌎, rest-api 🛰

#49 Feat/#20 implement lecture endpoint
  apps/java-api/src/main/java/org/scoalaonline/api/controller/LectureController.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/LectureInvalidTitleException.java
  apps/java-api/src/main/java/org/scoalaonline/api/exception/LectureNotFoundException.java
  apps/java-api/src/main/java/org/scoalaonline/api/model/Lecture.java
  apps/java-api/src/main/java/org/scoalaonline/api/repository/LectureRepository.java
  apps/java-api/src/main/java/org/scoalaonline/api/service/LectureService.java
Labels: docs ✏️, feat 🎸, wiki 🌎, rest-api 🛰

#64 docs: ✏️ update pull request template
  .github/pull_request_template.md
Labels: docs ✏️
